# Generated by Django 5.2.7 on 2026-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_status',
            field=models.CharField(default='в работе', max_length=100),
        ),
    ]
