# Generated by Django 5.2.7 on 2026-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_projectmodel_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_status',
            field=models.CharField(default='В работе', max_length=100),
        ),
    ]
