# Generated by Django 5.2.7 on 2026-02-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedpisaniyeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_predpisaniye', models.CharField(max_length=100)),
                ('date_create_predpisaniye', models.CharField(max_length=100)),
                ('name_counterparty', models.CharField(max_length=100)),
                ('name_object', models.CharField(max_length=100)),
                ('date_execution_predpisaniye', models.CharField(max_length=100)),
                ('execution_status', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number_predpisaniye'],
            },
        ),
    ]
