# Generated by Django 5.2.7 on 2026-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOyTB_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedpisaniyemodel',
            options={},
        ),
        migrations.AlterField(
            model_name='pedpisaniyemodel',
            name='date_execution_predpisaniye',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedpisaniyemodel',
            name='execution_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedpisaniyemodel',
            name='name_counterparty',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pedpisaniyemodel',
            name='name_object',
            field=models.CharField(max_length=700),
        ),
    ]
