# Generated by Django 5.2.7 on 2025-11-04 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sokr', models.CharField(max_length=100)),
                ('name_poln', models.CharField(max_length=100)),
                ('ur_adres', models.TextField(max_length=300)),
                ('pocht_adres', models.TextField(max_length=300)),
                ('inn', models.CharField(max_length=100)),
                ('kpp', models.CharField(max_length=100)),
                ('ogrn', models.CharField(max_length=100)),
                ('name_bank', models.CharField(max_length=100)),
                ('rs', models.CharField(max_length=100)),
                ('ks', models.CharField(max_length=100)),
                ('bik', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name_sokr', 'name_poln'],
            },
        ),
    ]
