# Generated by Django 5.2.7 on 2026-01-31 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyModelSRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sokr', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('ogrn', models.CharField(max_length=100)),
                ('name_sro', models.CharField(max_length=100)),
                ('reg_nymber_sro', models.CharField(max_length=100)),
                ('date_sro', models.CharField(max_length=100)),
                ('adres_sro', models.TextField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
