# Generated by Django 5.2.7 on 2026-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0003_counterpartymodelsroonpsd_counterpartymodelsroonsmr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartymodelsroonpsd',
            name='date_sro',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='counterpartymodelsroonsmr',
            name='date_sro',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
    ]
