# Generated by Django 5.2.7 on 2026-01-31 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0004_alter_counterpartymodelsroonpsd_date_sro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CounterpartyModelSROonPSD',
            new_name='SROonPSDModel',
        ),
        migrations.CreateModel(
            name='SROonSMRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sokr', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('ogrn', models.CharField(max_length=100)),
                ('name_poln_sro_on_smr', models.CharField(max_length=100)),
                ('name_sokr_sro_on_smr', models.CharField(max_length=100)),
                ('adres_sro_on_smr', models.TextField(max_length=300)),
                ('reg_nymber_in_gsro', models.CharField(max_length=100)),
                ('reg_nymber_in_sro', models.CharField(max_length=100)),
                ('date_sro', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации')),
                ('sr_1', models.CharField(max_length=100)),
                ('sr_2', models.CharField(max_length=100)),
                ('sr_3', models.CharField(max_length=100)),
                ('status_sr', models.CharField(max_length=100)),
                ('a_2', models.CharField(max_length=100)),
                ('b_2', models.CharField(max_length=100)),
                ('v_2', models.CharField(max_length=100)),
                ('g_2', models.CharField(max_length=100)),
                ('d_2', models.CharField(max_length=100)),
                ('e_2', models.CharField(max_length=100)),
                ('a_3', models.CharField(max_length=100)),
                ('b_3', models.CharField(max_length=100)),
                ('v_3', models.CharField(max_length=100)),
                ('g_3', models.CharField(max_length=100)),
                ('d_3', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CounterpartyModelSROonSMR',
        ),
    ]
