# Generated by Django 5.2.7 on 2026-01-31 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0005_rename_counterpartymodelsroonpsd_sroonpsdmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterpartymodel',
            name='type_of_counterparty',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
