# Generated by Django 5.2.7 on 2026-01-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0006_counterpartymodel_type_of_counterparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sroonsmrmodel',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='sroonsmrmodel',
            name='name_sokr',
        ),
        migrations.RemoveField(
            model_name='sroonsmrmodel',
            name='ogrn',
        ),
    ]
