# Generated by Django 5.2.7 on 2026-01-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0007_remove_sroonsmrmodel_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterpartymodel',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
