# Generated by Django 5.2.7 on 2026-01-31 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0008_counterpartymodel_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SROModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_poln_sro', models.CharField(max_length=100)),
                ('name_sokr_sro', models.CharField(max_length=100)),
                ('type_of_counterparty_sro', models.CharField(max_length=100)),
                ('ur_adres', models.TextField(max_length=300)),
                ('reg_nymber_in_grsro', models.CharField(max_length=100)),
                ('reg_nymber_in_rhsro', models.CharField(max_length=100)),
                ('date_reg_in_rhsro', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации')),
                ('stroitelstvo', models.CharField(max_length=100)),
                ('reconsrukcya', models.CharField(max_length=100)),
                ('kap_remont', models.CharField(max_length=100)),
                ('demontaj_kap_stroitelstva', models.CharField(max_length=100)),
                ('inj_iziscanya', models.CharField(max_length=100)),
                ('psd', models.CharField(max_length=100)),
                ('date_1', models.CharField(max_length=100)),
                ('date_2', models.CharField(max_length=100)),
                ('date_3', models.CharField(max_length=100)),
                ('a_2', models.CharField(max_length=100)),
                ('pred_summ_a_2', models.FloatField(max_length=100)),
                ('b_2', models.CharField(max_length=100)),
                ('pred_summ_b_2', models.FloatField(max_length=100)),
                ('v_2', models.CharField(max_length=100)),
                ('pred_summ_v_2', models.FloatField(max_length=100)),
                ('g_2', models.CharField(max_length=100)),
                ('pred_summ_g_2', models.FloatField(max_length=100)),
                ('d_2', models.CharField(max_length=100)),
                ('pred_summ_d_2', models.FloatField(max_length=100)),
                ('e_2', models.CharField(max_length=100)),
                ('pred_summ_e_2', models.FloatField(max_length=100)),
                ('a_3', models.CharField(max_length=100)),
                ('pred_summ_a_3', models.FloatField(max_length=100)),
                ('b_3', models.CharField(max_length=100)),
                ('pred_summ_b_3', models.FloatField(max_length=100)),
                ('v_3', models.CharField(max_length=100)),
                ('pred_summ_v_3', models.FloatField(max_length=100)),
                ('g_3', models.CharField(max_length=100)),
                ('pred_summ_g_3', models.FloatField(max_length=100)),
                ('d_3', models.CharField(max_length=100)),
                ('pred_summ_d_3', models.FloatField(max_length=100)),
                ('status_sro', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SROonSMRModel',
        ),
    ]
