# Generated by Django 5.2.7 on 2026-01-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0009_sromodel_delete_sroonsmrmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sromodel',
            name='date_1',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='date_2',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='date_3',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='date_reg_in_rhsro',
            field=models.DateField(auto_now=True, verbose_name='Дата регистрации'),
        ),
        migrations.DeleteModel(
            name='SROonPSDModel',
        ),
    ]
