# Generated by Django 5.2.7 on 2026-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounterpartyApp', '0010_alter_sromodel_date_1_alter_sromodel_date_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sromodel',
            old_name='type_of_counterparty_sro',
            new_name='date_vipiski_sro',
        ),
        migrations.AddField(
            model_name='sromodel',
            name='name_poln_counter',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sromodel',
            name='nymber_vipiski_sro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='date_reg_in_rhsro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='demontaj_kap_stroitelstva',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='inj_iziscanya',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='kap_remont',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='name_poln_sro',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='name_sokr_sro',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='psd',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='reconsrukcya',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sromodel',
            name='stroitelstvo',
            field=models.BooleanField(default=False),
        ),
    ]
