# Generated by Django 5.2.7 on 2026-09-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JurnalsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnalsmodel',
            options={'ordering': ['name_jurnals', 'public']},
        ),
    ]
