# Generated by Django 5.2.7 on 2026-09-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JurnalsApp', '0002_alter_jurnalsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='jurnalsmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='jurnalsmodel',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='jurnalsmodel',
            name='name_jurnals',
        ),
        migrations.RemoveField(
            model_name='jurnalsmodel',
            name='public',
        ),
        migrations.RemoveField(
            model_name='jurnalsmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('public1', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('categories', models.ManyToManyField(blank=True, to='JurnalsApp.category', verbose_name='Категории')),
            ],
        ),
    ]
