# Generated by Django 5.2.7 on 2026-09-19 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JurnalsApp', '0003_category_alter_jurnalsmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnalsmodel',
            options={'ordering': ['name_jurnals']},
        ),
        migrations.AddField(
            model_name='jurnalsmodel',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='jurnalsmodel',
            name='name_jurnals',
            field=models.CharField(default='Журнал', max_length=100),
        ),
        migrations.AddField(
            model_name='jurnalsmodel',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jurnalsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
